Repository F5Networks/f5-openstack-agent, pull requests merged in 2018-10, with the labels that each got.

#1337 Fix the wrong prerequisite version in agent doc
  docs/conf.py
Labels: documentation

#1338 only replace name with partiton when name is empty
  f5_openstack_agent/lbaasv2/drivers/bigip/network_helper.py
Labels: bug

#1345 Cherry-Pick: fix syntax error
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: bug

#1348 Fix the wrong prerequisite version in agent doc
  docs/conf.py
Labels: documentation

#1350 Fix the wrong prerequisite version in agent doc
  docs/conf.py
Labels: documentation

#1349 only replace name with partiton when name is empty
  f5_openstack_agent/lbaasv2/drivers/bigip/network_helper.py
Labels: bug

#1351 Update version to 9.6.6
  f5_openstack_agent/__init__.py
Labels: enhancement

#1358 Fix flake8 errors
  f5_openstack_agent/lbaasv2/drivers/bigip/exceptions.py
  f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/test/test_icontrol_driver_opts.py
Labels: blocked, test-bug

#1362 9.7.0 release note
  docs/RELEASE-NOTES.rst
Labels: documentation
