Repository F5Networks/f5-openstack-agent, pull requests merged in 2018-12, with the labels that each got.

#1386 Cherry pick 9.7
  f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py
Labels: bug

#1376 expose valid esd names via agent
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: enhancement

#1389 expose valid esd names via agent
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: feature

#1388 bugfix: select and use a global route domain id instead of local.
  .gitignore
  f5_openstack_agent/lbaasv2/drivers/bigip/network_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
  test/functional/singlebigip/test_network.py
Labels: bug

#1393 bugfix: select and use a global route domain id instead of local.
  f5_openstack_agent/__init__.py
  f5_openstack_agent/lbaasv2/drivers/bigip/network_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
  test/functional/singlebigip/test_network.py
Labels: bug

#1395 update 9.8.0 version and release note.
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: enhancement

#1397 update release note
  docs/RELEASE-NOTES.rst
Labels: documentation

#1396 update travis.yml for multiple product document generation.
  .travis.yml
Labels: documentation

#1398 fix the travis build issue.
  docs/RELEASE-NOTES.rst
Labels: documentation

#1399 fix version from vv9.8 to v9.8 when publish docs.
  .travis.yml
Labels: bug
