Repository F5Networks/f5-openstack-agent, pull requests merged in 2020-11, with the labels that each got.

#1513 Create v9.8.18 release
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1515 Create http_cookie and source_addr persistence profile
  f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1520 Revert "fix bug: delete lb will delete route domain and partition."
  .travis.yml
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: bug

#1516 fix: L2 mode HA sync bug.（test in vlan and vxlan）
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: bug

#1521 Create 9.18.19 release
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1517 create a dedicated http profile for a listener
  etc/neutron/services/f5/f5-extended-profile.json
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1523 Add TERMINATED_HTTPS protocol type vs support
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1528 install f5-extended-profile.json
  setup.py
Labels: agent-lite

#1529 Revert "install f5-extended-profile.json"
  setup.py
Labels: agent-lite

#1525 fix: bigip device down, the whole process exit
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: bug

#1532 feat: add ftp function for 2.0
  f5_openstack_agent/lbaasv2/drivers/bigip/ftp_profile.py
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_builder.py
  f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py
  f5_openstack_agent/lbaasv2/drivers/bigip/test/test_listener_services.py
Labels: feature

#1533 feat: add ftp function for agent 3.0
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: feature

#1514 Cherry-pick config changes from v9.8.16 to 9.8-stable
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
Labels: enhancement

#1534 Revert "Revert "fix: L2 mode HA sync bug.（test in vlan and vxlan）""
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: bug

#1524 Support L7Policy
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1535 Set http cookie expiration value
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1536 check the pool id when creating members in batch.
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1538 Add a log to print active bigips hosts
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: enhancement

#1539 avoid creating duplicated http profile
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1540 Update persist profile in all active bigips
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1542 Assign initial value of persist variable
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1543 Create 9.8.20 release
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1541 fix: VS is not bond to correct VIP in L2 mode
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1546 dependency package not found; agent can not be started
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1548 Support listener protocol port 0
  f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py
Labels: enhancement

#1544 Add supporting to update listener with tls changes.
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite
