Repository F5Networks/f5-openstack-agent, pull requests merged in 2021-09, with the labels that each got.

#1774 add a periodic config save task
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
Labels: bug

#1779 [OPENSTACK-2282]Fix resources creation conflict issue.
  f5_openstack_agent/lbaasv2/drivers/bigip/l2_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: bug

#1780 [OPENSTACK-2282]Fix resource creation conflict issue.
  f5_openstack_agent/lbaasv2/drivers/bigip/l2_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: bug

#1782 [OPENSTACK-2282] Fix snat creation conflict issue. (9.8.47)
  f5_openstack_agent/lbaasv2/drivers/bigip/l2_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: bug

#1783 [OPENSTACK-2282] Cleanup redundant neutron port of self ip and snat ip
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: bug

#1784 [OPENSTACK-2282] Cleanup redundant neutron port of self ip and snat ip (9.8.47)
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: bug

#1785 [OPENSTACK-2282] Cleanup redundant neutron port of self ip and snat ip (9.9)
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: bug

#1786 [OPENSTACK-2286] Modify 9.8.47 release note
  docs/RELEASE-NOTES.rst
Labels: documentation

#1787 [OPENSTACK-2286] Modify 9.8.47 release note (9.8.47)
  docs/RELEASE-NOTES.rst
Labels: documentation

#1791 fix: multiple agents updating snatpool member causes bigip incosistency problem
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: multi-agent-bug

#1792 fix: multiple agents updating snatpool member causes bigip incosistency problem
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: multi-agent-bug

#1788 [OPENSTACK-2295] Ensure route domain id consistency
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: bug

#1794 [OPENSTACK-2295] Ensure route domain id consistency
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: bug

#1795 [OPENSTACK-2286] Modify 9.8.47 release note
  docs/RELEASE-NOTES.rst
Labels: documentation

#1796 [OPENSTACK-2286] Modify 9.8.47 release note
  docs/RELEASE-NOTES.rst
Labels: documentation

#1799 Revert "[OPENSTACK-2282] Cleanup redundant neutron port of self ip and snat ip (9.8.47)"
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: bug

#1797 Revert "[OPENSTACK-2282] Cleanup redundant neutron port of self ip and snat ip"
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: bug

#1798 Revert "[OPENSTACK-2282] Cleanup redundant neutron port of self ip and snat ip (9.9)"
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: bug

#1800 [OPENSTACK-2286] Modify 9.8.47 release note
  docs/RELEASE-NOTES.rst
Labels: documentation

#1801 [OPENSTACK-2286] Modify 9.8.47 release note
  docs/RELEASE-NOTES.rst
Labels: documentation
