Repository F5Networks/f5-openstack-agent, pull requests merged in 2021-06, with the labels that each got.

#1731 Revert "(WIP) Refactor extended profile implementation"
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1733 fix iRule for blacklist, the 'eq' is missing
  f5_openstack_agent/lbaasv2/drivers/bigip/acl.py
Labels: bug

#1732 Refactor extended profile implementation
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite, enhancement

#1736 prerelease v9.9.30
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1738 Revert "Refactor extended profile implementation"
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1739 Release note update: no bugfix.
  docs/RELEASE-NOTES.rst
Labels: prerelease

#1743 Avoid patching profile failure, if profile is not created
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1735 http2 profile support
  etc/neutron/services/f5/f5-extended-profile.json
  f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py
  f5_openstack_agent/lbaasv2/drivers/bigip/ssl_profile.py
  f5_openstack_agent/lbaasv2/drivers/bigip/test/test_listener_services.py
  f5_openstack_agent/lbaasv2/drivers/bigip/test/test_ssl_profile.py
Labels: agent-lite, enhancement

#1746 Fix: if member is existed, it will cause HTTP 409 ERROR
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1748 Fix: if member is existed, it will cause HTTP 409 ERROR (Cherry-pick from 9.8-stable)
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1737 Support websocket profile
  deb_setup_requirements.txt
  docs/conf.py
  etc/neutron/services/f5/f5-extended-profile.json
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  rpm_setup_requirements.txt
  setup.py
Labels: agent-lite, enhancement

#1752 fix: add rule and remove rule for ACLGroup
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1747 fix Illformed requirement ["~> >=1.0.1-1ubuntu1~clo"]
  deb_setup_requirements.txt
Labels: bug

#1754 fix Illformed requirement ["~> >=1.0.1-1ubuntu1~clo"]
  deb_setup_requirements.txt
Labels: bug
