Repository F5Networks/f5-openstack-agent, pull requests merged in 2021-02, with the labels that each got.

#1641 Correct the log type (9.8)
  f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py
Labels: bug

#1642 Correct the log type (9.9)
  f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py
Labels: bug

#1649 Add server/client tcp profile
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/irule.py
  f5_openstack_agent/lbaasv2/drivers/bigip/l7policy_adapter.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tcp_profile.py
Labels: feature

#1650 Release 9.9.2
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1648 Support l7policy REDIRECT_TO_HOST action (toubiao)
  f5_openstack_agent/lbaasv2/drivers/bigip/l7policy_adapter.py
Labels: agent-lite, enhancement

#1651 Error loadbalancer cannot be deleted
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
Labels: bug

#1654 Fix the issue of route domain issue: id already exists.
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: agent-lite, bug

#1652 Fix the issue of route domain issue: id already exists.
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: agent-lite, bug

#1655 release v9.8.45
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1656 Release v9.8.45
  docs/RELEASE-NOTES.rst
Labels: prerelease
