Repository F5Networks/f5-openstack-agent, pull requests merged in 2021-11, with the labels that each got.

#1811 fix: get all nodes in a partition
  f5_openstack_agent/lbaasv2/drivers/bigip/network_helper.py
Labels: bug

#1813 [OPENSTACK-2342] fix: selfip recreating is unabled to catch HTTP 409
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
Labels: bug

#1814 pre release 9.9.41
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1816 [OPENSTACK-2343] Support uppercase cipher policy name
  f5_openstack_agent/lbaasv2/drivers/bigip/ssl_profile.py
Labels: enhancement

#1823 [OPENSTACK-2349] Support redirect LTM policy (9.8)
  f5_openstack_agent/lbaasv2/drivers/bigip/ltm_policy.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: enhancement
