Repository F5Networks/f5-openstack-agent, pull requests merged in 2021-03, with the labels that each got.

#1662 Fix the KeyError issue caused by heartbeat periodic task.
  f5_openstack_agent/lbaasv2/drivers/bigip/l2_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: agent-lite, bug

#1664 Fix the KeyError issue caused by heartbeat periodic task.
  f5_openstack_agent/lbaasv2/drivers/bigip/l2_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/selfips.py
  f5_openstack_agent/lbaasv2/drivers/bigip/snats.py
Labels: agent-lite, bug

#1663 convert bandwidth from string to int
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite

#1668 change travis images
  .travis.yml
Labels: enhancement

#1669 change travis images
  .travis.yml
Labels: enhancement

#1670 change travis images
  .travis.yml
Labels: enhancement

#1674 prerelease 3.0.1
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1629 a tool update-lb for updating lb status
  f5_openstack_agent/lbaasv2/drivers/bigip/update_lb.py
  setup.py
Labels: enhancement
