Repository F5Networks/f5-openstack-agent, pull requests merged in 2021-05, with the labels that each got.

#1697 multiple agents update the members in order
  f5_openstack_agent/lbaasv2/drivers/bigip/agent.py
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
Labels: agent-lite, enhancement

#1699 Do not use passive voice in release note
  docs/RELEASE-NOTES.rst
Labels: bug

#1695 bigip status check
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: agent-lite, bug, enhancement

#1700 bigip status check
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: bug

#1706 binding logging profile to http/terminated_https vs.
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: enhancement, feature

#1703 binding logging profile to http/terminated_https vs.
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: enhancement, feature

#1696 Cleanup all snat, vlan and self ip before removing partition (9.8-stable)
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: bug

#1708 Only check nodes in current partition (9.8-stable)
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: bug

#1710 Catch all exception for route domain creation.
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: bug

#1711 Catch all exception for route domain creation.
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: bug

#1712 Revert "binding logging profile to http/terminated_https vs."
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: duplicate, feature

#1716 Fix the issue of deleting nodes and snat in bigip ha mode.
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1719 Fix the issue of deleting nodes and snat in bigip ha mode.
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1724 Revert "Revert "binding logging profile to http/terminated_https vs.""
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: feature

#1715 Upgrade eventlet to version 0.31.0 for Dependabot vulnerable.
  requirements.functest.txt
  requirements.unittest.txt
Labels: enhancement

#1714 Upgrade eventlet to version 0.31.0 for Dependabot vulnerable.
  requirements.functest.txt
  requirements.unittest.txt
Labels: enhancement

#1728 v9.8.46 prerelease
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: prerelease

#1727 Add acl_group
  f5_openstack_agent/lbaasv2/drivers/bigip/acl.py
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: feature

#1707 Support cipher options
  f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py
  f5_openstack_agent/lbaasv2/drivers/bigip/ssl_profile.py
  f5_openstack_agent/lbaasv2/drivers/bigip/test/test_listener_services.py
  f5_openstack_agent/lbaasv2/drivers/bigip/test/test_ssl_profile.py
Labels: agent-lite, enhancement

#1718 add flavor:connection limit and rate limit
  f5_openstack_agent/lbaasv2/drivers/bigip/agent.py
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py
Labels: agent-lite, feature

#1729 (WIP) Refactor extended profile implementation
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: agent-lite, enhancement
