Repository F5Networks/f5-openstack-agent, pull requests merged in 2022-11, with the labels that each got.

#1967 [OPENSTACK-2603] Cap tox version (9.10)
  .travis.yml
Labels: enhancement

#1968 [OPENSTACK-2603] Cap tox version (9.9)
  .travis.yml
Labels: enhancement

#1965 [OPENSTACK-2603] encrypt bigip username and password.
  f5_openstack_agent/client/bigip.py
  f5_openstack_agent/client/clientmanager.py
  f5_openstack_agent/client/encrypt.py
  f5_openstack_agent/lbaasv2/drivers/bigip/bigip_device.py
Labels: NG

#1969 [OPENSTACK-2626]raise exception when bigip status is not both active
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1971 [OPENSTACK-2626]raise exception when two bigips status are not both a…
  .travis.yml
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1970 [OPENSTACK-2626]raise exception when two bigips status are not both a…
  .travis.yml
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1966 [OPENSTACK-2441] listener support keepalive_timeout
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tcp_profile.py
Labels: NG
