Repository F5Networks/f5-openstack-agent, pull requests merged in 2022-08, with the labels that each got.

#1886 [OPENSTACK-2546] Release 9.9.54
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: documentation

#1887 [OPENSTACK-2546] Change github API key
  .travis.yml
Labels: enhancement

#1888 [OPENSTACK-2546] Change github API key
  .travis.yml
Labels: enhancement

#1889 [OPENSTACK-2546] Change github API key (9.8)
  .travis.yml
  requirements.unittest.txt
Labels: enhancement

#1910 [OPENSTACK-2566] Reserve one floating ip in large snat subnet (9.9)
  f5_openstack_agent/lbaasv2/drivers/bigip/constants_v2.py
Labels: enhancement

#1911 [OPENSTACK-2566] Reserve one floating ip in large snat subnet (9.10)
  f5_openstack_agent/lbaasv2/drivers/bigip/constants_v2.py
Labels: enhancement

#1915 OPENSTACK-2559: purge bigip recover code
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/lbaas_driver.py
Labels: NG

#1916 OPENSTACK-2559: purge service sync code
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
Labels: NG

#1917 OPENSTACK-2522: fix help document
  f5_openstack_agent/bin/README.md
  f5_openstack_agent/bin/masquerade_mac.py
Labels: bug

#1918 OPENSTACK-2559: purge periodic-resync
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
Labels: NG

#1920 OPENSTACK-2559: purge bigip connection
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
Labels: NG
