Repository F5Networks/f5-openstack-agent, pull requests merged in 2022-12, with the labels that each got.

#1978 [OPENSTACK-2638] Enable iControl token authentication (9.9)
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/utils/clean_partition.py
Labels: enhancement

#1977 [OPENSTACK-2638] Enable iControl token authentication (9.10)
  f5_openstack_agent/client/clientmanager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
  f5_openstack_agent/lbaasv2/drivers/bigip/bigip_device.py
  f5_openstack_agent/utils/clean_partition.py
Labels: enhancement

#1979 [OPENSTACK-2571] Append route domain id to member node name (9.10)
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1980 [OPENSTACK-2571] Append route domain id to member node name (9.9)
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1974 [OPENSTACK-2441] listener support keepalive_timeout, fix missing othe…
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tcp_profile.py
Labels: bug

#1981 [OPENSTACK-2632] fix when update http2 filtered clientside tcp profile
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1976 [OPENSTACK-2610]listener support proxy protocol
  f5_openstack_agent/lbaasv2/drivers/bigip/irule.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: NG

#1982 [OPENSTACK-2636] Release v9.10.2
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: documentation

#1983 [OPENSTACK-2646] Fix rate limit debug log (9.10)
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1984 [OPENSTACK-2646] Fix rate limit debug log (9.9)
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#1986 [OPENSTACK-2646] Multi-zone agent
  f5_openstack_agent/client/bigip.py
Labels: enhancement
