Repository F5Networks/f5-openstack-agent, pull requests merged in 2023-02, with the labels that each got.

#1997 [OPENSTACK-2671] Encode confd password
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
Labels: enhancement

#1998 [OPENSTACK-2671] Encrypt password by python fernet
  bin/encrypt
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  setup.py
Labels: enhancement

#2003 [OPENSTACK-2624] Fix python 3 error in travis
  .travis.yml
Labels: enhancement

#2005 [OPENSTACK-2624] Fix python 3 error in travis (9.9)
  .travis.yml
Labels: enhancement

#2006 [OPENSTACK-2624] Fix python 3 error in travis (9.8)
  .travis.yml
Labels: enhancement

#2008 [openstack-2698]Agent timeout parameter change to apply to python req…
  f5_openstack_agent/lbaasv2/drivers/bigip/constants_v2.py
Labels: bug

#2007 [OPENSTACK-2697]Make the onboard command line argument format uniform
  f5_openstack_agent/client/bigip-onboard-cli.md
  f5_openstack_agent/client/bigip.py
Labels: NG
