Repository F5Networks/f5-openstack-agent, pull requests merged in 2023-10, with the labels that each got.

#2108 [OPENSTACK-2901] Add source ip port persistence support.
  f5_openstack_agent/lbaasv2/drivers/bigip/listener_service.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
  f5_openstack_agent/lbaasv2/drivers/bigip/service_adapter.py
Labels: enhancement, agent-lite

#2117 [OPENSTACK-2879] Remove redundant deleting route domain or loading selfip action
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: enhancement

#2053 [OPENSTACK-2787] Occupy device
  f5_openstack_agent/lbaasv2/drivers/bigip/agent_manager_lite.py
  f5_openstack_agent/lbaasv2/drivers/bigip/opts.py
  f5_openstack_agent/lbaasv2/drivers/bigip/plugin_rpc.py
Labels: enhancement

#2118 [OPENSTACK-2910] Listener support rewrite_xff.
  f5_openstack_agent/lbaasv2/drivers/bigip/irule.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: NG

#2132 [OPENSTACK-2879] Only delete empty route domain
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: bug
