Repository F5Networks/f5-openstack-agent, pull requests merged in 2023-08, with the labels that each got.

#2073 [OPENSTACK-2823] Release 9.10.5
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: NG

#2083 [OPENSTACK-2859] Retry 401 when initialize bigip and cleanup partition
  f5_openstack_agent/lbaasv2/drivers/bigip/bigip_device.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/tenants.py
Labels: enhancement

#2085 [OPENSTACK-2860] TOA tcp option setting for IPv4 and IPv6 separately …
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/irule.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: NG

#2087 [OPENSTACK-2860] Remove TOA irule log.
  f5_openstack_agent/lbaasv2/drivers/bigip/irule.py
Labels: NG

#2089 Toa
  etc/neutron/services/f5/f5-openstack-agent.ini
  f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py
  f5_openstack_agent/lbaasv2/drivers/bigip/irule.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: NG

#2093 [OPENSTACK-2867] Fix creating vlan racing problem
  f5_openstack_agent/lbaasv2/drivers/bigip/network_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#2094 [OPENSTACK-2867] Fix creating vlan racing problem (9.10.5)
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/lbaasv2/drivers/bigip/network_helper.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource.py
  f5_openstack_agent/lbaasv2/drivers/bigip/resource_manager.py
Labels: bug

#2096 [OPENSTACK-2866] Remove obsolete inventory code.
  f5_openstack_agent/client/__init__.py
  f5_openstack_agent/client/bigip-onboard-cli.md
  f5_openstack_agent/client/bigip.py
  f5_openstack_agent/client/clientmanager.py
  f5_openstack_agent/client/shell.py
  f5_openstack_agent/lbaasv2/drivers/bigip/bigip_device.py
  f5_openstack_agent/lbaasv2/drivers/bigip/monitor_manager.py
  f5_openstack_agent/utils/encrypt.py
  setup.py
Labels: NG
