Repository F5Networks/f5-openstack-agent, pull requests merged in 2023-12, with the labels that each got.

#2151 [OPENSTACK-2905] New implementation of flavor 1-6 SNAT
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: enhancement

#2161 [OPENSTACK-2939] Ignore 400 error of deleting route domain when concu…
  f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py
Labels: bug

#2162 [OPENSTACK-2941] Release 9.10.6.1
  docs/RELEASE-NOTES.rst
  f5_openstack_agent/__init__.py
Labels: NG
